### ISSUE TITLE
[4.3:35] The system shall support the braille code used in Denmark, Finland, Norway, Sweden and Switzerland for 8-dot braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#14]
### Requirements

[[4.3:35]](http://snaekobbi.github.io/requirements#4.3:35) The system shall support the braille code used in Denmark, Finland, Norway, Sweden and Switzerland for 8-dot braille.
[[4.3:35B]](http://snaekobbi.github.io/requirements#4.3:35B) The system shall support the braille code used in the Netherlands for 8-dot braille.
### Tasks
- [ ] re-evaluate requirement/priority of 8-dot braille for the various languages (@BWestling + @bertfrees)

**Comment by BWestling** [comment]
I imagine that support for 8-dot braille is available in Liblouis for some, but not all, of the languages DK, FI, NO and DE. Am I right? For SE we would like to support 8-dot braille. Need to consult Joel for how to do it though (in Dotify?).

Downgrade 4.3:35 to prio 2?

Davy has written that there is no 8-dot braille code in the Netherlands (for NL). 4.3:35B should be prio 3 accordingly.

**Comment by bertfrees** [comment]
The problem is actually that for several languages no definition of 8-dot braille exists (or not known by the agency). For which languages a definition exist and for which not is still not completely clear to me.
- Danish: yes
- Dutch: no (see https://github.com/snaekobbi/requirements/issues/42#issuecomment-118005327)
- German: ?
- Finnish: no (see https://github.com/snaekobbi/requirements/pull/4#issuecomment-70238498)
- Norwegian: ?
- Swedish: ?

It seems that Liblouis has support for 8-dot braille in Danish, Finnish and German (although I'm not sure if these tables are following an official standard, e.g. Jukka said 8-dot braille doesn't officially exist for Finnish).

**Comment by BWestling** [comment]
I could send question about it to the braille authorities (in the Nordic countries at least).

**Comment by bertfrees** [comment]
OK, that would be great.

**Comment by mixa72** [comment]
For German, there is no official definition of 8-dot braille, but there is a good overview on http://www.braille.ch/eb-id-vf.htm. The mapping seems to correspond to Liblouis' de-de-comp8.ctb table.

**Comment by dkager** [comment]
In The Netherlands, most people use either the US or German 8-dot tables. I would be interested in validating and expanding these (especially US), albeit not for immediate use in the embossing process. The US 8-dot table is ‘woefully inadequate’ right now.

**Comment by josteinaj** [comment]
@bertfrees: Norwegian 8-dot spec is specified by mapping each of the 256 8-dot braille characters to Windows code page 1252. The spec was uploaded earlier and is available here: https://github.com/liblouis/braille-specs/tree/master/norwegian#8-punktstabell

@usama49 and I created a table based on it.
- table: https://github.com/snaekobbi/liblouis/blob/1f703b64cfe070bd04de9acefd59531cdd314827/tables/no-no-8dot.utb
- tests: https://github.com/snaekobbi/liblouis/blob/1f703b64cfe070bd04de9acefd59531cdd314827/tests/harness/no_harness_8dot.txt

@bertfrees: the test currently fail mainly because we need to figure out how to fall back to the norwegian 6-dot (uncontracted) table for characters not defined in 8-dot.

There's also a couple of characters that liblouis fails to translate it seems:
- [escape character](http://unicode-table.com/en/001B/)
- [no-break space](http://unicode-table.com/en/00A0/)
