### ISSUE TITLE
[4.7:94] The system shall support formatting of numbers and other variables in a wide selection of formats…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#74]
### Requirement

[[4.7:94]](http://snaekobbi.github.io/requirements#4.7:94) The system shall support formatting of numbers and other variables in a wide selection of formats. Supported formats shall include at least arabic, roman (small and capital), alpha (small and capital), downshifted, written out, and various date formats. It shall be possible to specify number prefixes and suffixes too. Some numbers might need specialized translation, such as ranges of print pages.
## sprint#4 [:fast_forward:](https://github.com/snaekobbi/sprints/issues/147)

In this sprint we deal only with braille page numbers.
### Tasks
- [x] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- DE: Self-defined counter not working

**Comment by bertfrees** [comment]
> Self-defined counter not working.

@mixa Can you explain a bit more what exactly you tried and what went wrong?

**Comment by mixa72** [comment]
Hi Bert,

I tried to output and repeatedly reset different number formats (arabic, roman, downshifted) in the footer (see attachment). In order to get a downshifted number format, I defined a counter-style according to the description in the CSS specification but it seems not to work. Maybe there is a mistake in my CSS. Could you check that?
Thank you

Regards,
Mischa

**Comment by bertfrees** [comment]
OK I see what you were trying to do. The CSS is 100% correct, but unfortunately this is not implemented yet. Don't throw away this test, we can use it later, maybe we'll implement it next sprint.
